// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetRadar.Core.Data;

#nullable disable

namespace PetRadar.DbMigrations.Migrations
{
    [DbContext(typeof(PetRadarDbContext))]
    [Migration("20260211184952_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 11, 18, 49, 51, 573, DateTimeKind.Unspecified).AddTicks(6752), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            Email = "sa@test.com",
                            EmailVerified = true,
                            IsActive = true,
                            LastName = "Admmin",
                            Name = "Super",
                            Password = new byte[] { 22, 223, 6, 175, 6, 237, 131, 89, 247, 3, 227, 36, 100, 37, 223, 233, 203, 148, 38, 207, 40, 135, 179, 126, 236, 211, 100, 113, 162, 98, 98, 76, 152, 30, 0, 202, 142, 226, 253, 19, 187, 20, 89, 28, 119, 47, 89, 126, 81, 221, 16, 86, 77, 82, 107, 165, 188, 4, 201, 122, 169, 190, 136, 40, 150, 160, 14, 164, 40, 203, 46, 151, 193, 151, 80, 163, 244, 38, 169, 205, 50, 101, 9, 2, 207, 138, 242, 86, 191, 243, 206, 210, 65, 231, 108, 100, 141, 215, 131, 65, 34, 107, 233, 144, 37, 107, 76, 1, 98, 178, 174, 88, 2, 14, 249, 169, 89, 143, 142, 81, 210, 235, 31, 40, 167, 29, 116, 223, 122, 244, 255, 155, 50, 248, 223, 200, 42, 23, 215, 121, 103, 218, 58, 223, 128, 129, 117, 146, 3, 231, 189, 184, 19, 11, 45, 253, 237, 27, 210, 136, 241, 187, 16, 103, 118, 115, 58, 185, 148, 1, 49, 109, 165, 83, 16, 77, 234, 0, 71, 25, 112, 147, 185, 57, 220, 191, 27, 128, 186, 192, 241, 219, 203, 126, 220, 25, 214, 63, 186, 190, 195, 23, 41, 144, 59, 142, 151, 48, 225, 193, 25, 126, 251, 224, 239, 204, 177, 207, 138, 18, 52, 32, 119, 7, 165, 167, 218, 61, 253, 19, 40, 72, 148, 106, 167, 27, 70, 167, 210, 246, 185, 69, 84, 98, 254, 158, 169, 205, 34, 55, 196, 163, 126, 50, 79, 39 },
                            PhoneNumber = "000000000",
                            Role = "SuperAdmin",
                            Salt = new byte[] { 96, 214, 217, 231, 53, 149, 247, 148, 10, 126, 221, 249, 168, 65, 141, 97, 116, 6, 216, 196, 156, 27, 13, 87, 119, 76, 220, 82, 155, 43, 223, 111, 144, 39, 188, 242, 99, 31, 113, 85, 116, 115, 215, 41, 134, 217, 170, 116, 25, 201, 49, 79, 247, 151, 229, 31, 198, 214, 57, 8, 31, 170, 183, 72, 216, 191, 20, 60, 226, 152, 220, 140, 75, 125, 154, 51, 143, 186, 12, 109, 195, 224, 70, 26, 56, 108, 194, 157, 231, 200, 71, 63, 16, 206, 55, 89, 11, 30, 27, 118, 197, 124, 140, 161, 36, 162, 12, 131, 217, 128, 184, 145, 230, 78, 216, 7, 96, 211, 75, 241, 95, 126, 110, 51, 97, 42, 85, 138 },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 11, 18, 49, 51, 573, DateTimeKind.Unspecified).AddTicks(6752), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = 0L
                        });
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserPetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalPhotosURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Allergies")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("ApproximateAge")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNeutered")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPets");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserPetEntity", b =>
                {
                    b.HasOne("PetRadar.Core.Data.Entities.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });
#pragma warning restore 612, 618
        }
    }
}
