// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetRadar.Core.Data;

#nullable disable

namespace PetRadar.DbMigrations.Migrations
{
    [DbContext(typeof(PetRadarDbContext))]
    [Migration("20260224220120_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetRadar.Core.Data.Entities.AdoptionAnimalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalPhotosURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("AdopterId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("AdoptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ApproximateAge")
                        .HasColumnType("numeric");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("GoodWithCats")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GoodWithDogs")
                        .HasColumnType("boolean");

                    b.Property<bool?>("GoodWithKids")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNeutered")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVaccinated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("NeedsSpecialCare")
                        .HasColumnType("boolean");

                    b.Property<string>("Personality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<long>("ShelterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("SpecialCareDetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId");

                    b.HasIndex("ShelterId");

                    b.ToTable("AdoptionAnimals");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 24, 22, 1, 19, 464, DateTimeKind.Unspecified).AddTicks(467), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            Email = "sa@test.com",
                            EmailVerified = true,
                            IsActive = true,
                            LastName = "Admmin",
                            Name = "Super",
                            Password = new byte[] { 190, 177, 99, 44, 149, 154, 30, 167, 62, 157, 69, 173, 137, 118, 80, 222, 14, 237, 156, 72, 41, 82, 60, 122, 185, 249, 36, 230, 136, 124, 181, 78, 27, 103, 60, 198, 156, 144, 147, 140, 209, 170, 65, 221, 225, 179, 222, 48, 24, 231, 109, 59, 21, 236, 43, 124, 193, 4, 66, 1, 195, 148, 94, 230, 234, 26, 123, 153, 140, 157, 69, 214, 133, 17, 67, 207, 12, 149, 165, 205, 197, 248, 51, 115, 184, 204, 210, 32, 172, 222, 41, 24, 136, 125, 113, 246, 160, 144, 21, 172, 193, 43, 249, 146, 158, 246, 164, 157, 16, 251, 190, 120, 207, 12, 174, 11, 205, 140, 30, 14, 129, 232, 234, 77, 164, 220, 234, 6, 141, 228, 116, 147, 193, 90, 26, 117, 109, 120, 8, 64, 148, 159, 144, 58, 50, 179, 36, 83, 20, 151, 123, 153, 29, 216, 3, 34, 65, 112, 115, 121, 140, 89, 244, 222, 13, 54, 50, 227, 210, 156, 183, 114, 124, 2, 53, 88, 64, 48, 65, 74, 117, 234, 53, 21, 86, 163, 73, 76, 101, 158, 42, 158, 8, 130, 52, 81, 149, 127, 90, 217, 158, 190, 37, 51, 245, 133, 41, 114, 125, 235, 167, 172, 132, 120, 41, 243, 165, 4, 78, 8, 217, 155, 130, 20, 210, 152, 224, 118, 87, 65, 191, 121, 47, 36, 69, 142, 202, 162, 8, 163, 187, 91, 144, 61, 53, 17, 138, 159, 96, 74, 220, 101, 148, 150, 234, 180 },
                            PhoneNumber = "000000000",
                            Role = "SuperAdmin",
                            Salt = new byte[] { 232, 8, 80, 43, 199, 126, 2, 172, 208, 120, 144, 96, 53, 52, 57, 169, 248, 105, 24, 5, 217, 1, 138, 65, 93, 123, 114, 255, 7, 162, 63, 37, 189, 205, 183, 147, 241, 106, 199, 66, 185, 13, 85, 114, 152, 38, 76, 73, 51, 142, 157, 117, 15, 117, 207, 135, 240, 71, 233, 185, 201, 120, 67, 250, 247, 64, 163, 82, 49, 101, 105, 174, 244, 81, 2, 132, 9, 9, 1, 110, 159, 226, 28, 14, 208, 52, 20, 155, 11, 70, 220, 174, 143, 97, 80, 22, 181, 0, 219, 0, 16, 151, 170, 65, 218, 100, 217, 224, 111, 204, 36, 156, 198, 177, 115, 73, 174, 56, 97, 28, 66, 28, 172, 116, 172, 173, 61, 78 },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 24, 22, 1, 19, 464, DateTimeKind.Unspecified).AddTicks(467), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = 0L
                        });
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserPetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalPhotosURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Allergies")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("ApproximateAge")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNeutered")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPets");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.VeterinaryAppointmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prescriptions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Treatment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("VeterinaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("VeterinaryAppointments");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.AdoptionAnimalEntity", b =>
                {
                    b.HasOne("PetRadar.Core.Data.Entities.UserEntity", "AdopterUser")
                        .WithMany()
                        .HasForeignKey("AdopterId");

                    b.HasOne("PetRadar.Core.Data.Entities.UserEntity", "ShelterUser")
                        .WithMany()
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdopterUser");

                    b.Navigation("ShelterUser");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserPetEntity", b =>
                {
                    b.HasOne("PetRadar.Core.Data.Entities.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.VeterinaryAppointmentEntity", b =>
                {
                    b.HasOne("PetRadar.Core.Data.Entities.UserPetEntity", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
