// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetRadar.Core.Data;

#nullable disable

namespace PetRadar.DbMigrations.Migrations
{
    [DbContext(typeof(PetRadarDbContext))]
    partial class PetRadarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OrganizationPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("bytea");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProfilePhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 17, 17, 54, 2, 76, DateTimeKind.Unspecified).AddTicks(535), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = 1L,
                            Email = "sa@test.com",
                            EmailVerified = true,
                            IsActive = true,
                            LastName = "Admmin",
                            Name = "Super",
                            Password = new byte[] { 14, 22, 111, 213, 164, 153, 70, 52, 101, 117, 196, 229, 2, 191, 251, 13, 92, 114, 160, 125, 91, 176, 88, 118, 77, 21, 146, 250, 253, 0, 138, 202, 67, 59, 156, 122, 96, 234, 73, 66, 20, 206, 11, 67, 110, 190, 247, 237, 169, 106, 106, 209, 134, 101, 152, 86, 198, 157, 224, 116, 252, 189, 235, 77, 18, 23, 37, 0, 58, 76, 83, 185, 95, 157, 139, 211, 70, 74, 148, 53, 214, 250, 1, 201, 117, 251, 146, 44, 159, 243, 186, 168, 196, 74, 207, 174, 163, 124, 236, 194, 41, 0, 126, 109, 22, 47, 58, 170, 150, 163, 172, 151, 187, 101, 133, 28, 170, 152, 111, 96, 150, 218, 231, 70, 92, 126, 219, 243, 72, 6, 132, 24, 134, 134, 111, 206, 212, 193, 66, 95, 104, 138, 109, 51, 64, 82, 211, 132, 135, 127, 123, 85, 122, 97, 60, 65, 227, 159, 59, 64, 169, 26, 32, 211, 71, 94, 169, 88, 213, 161, 242, 63, 2, 141, 35, 229, 24, 197, 99, 185, 81, 230, 246, 64, 233, 186, 250, 37, 1, 222, 132, 168, 228, 237, 247, 23, 92, 88, 51, 102, 8, 205, 49, 18, 141, 3, 185, 20, 233, 254, 74, 18, 207, 42, 1, 240, 202, 142, 229, 54, 120, 174, 138, 125, 153, 105, 134, 169, 54, 123, 168, 153, 146, 227, 94, 41, 212, 253, 39, 235, 233, 78, 23, 175, 36, 125, 211, 132, 169, 34, 83, 236, 219, 21, 48, 209 },
                            PhoneNumber = "000000000",
                            Role = "SuperAdmin",
                            Salt = new byte[] { 229, 183, 112, 99, 219, 171, 145, 157, 124, 44, 79, 255, 60, 124, 254, 168, 205, 107, 162, 67, 7, 252, 162, 1, 185, 222, 177, 181, 208, 79, 242, 109, 118, 169, 44, 188, 93, 243, 180, 83, 124, 70, 254, 177, 143, 199, 194, 98, 2, 252, 229, 193, 132, 217, 5, 202, 70, 43, 157, 233, 159, 86, 170, 221, 34, 28, 244, 233, 237, 77, 83, 82, 54, 172, 3, 204, 27, 195, 102, 203, 46, 253, 5, 142, 70, 200, 14, 195, 81, 159, 207, 126, 48, 158, 177, 248, 38, 37, 27, 104, 13, 58, 193, 158, 216, 234, 242, 165, 196, 156, 227, 227, 241, 20, 18, 17, 104, 127, 52, 184, 159, 111, 71, 16, 150, 22, 80, 221 },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 2, 17, 17, 54, 2, 76, DateTimeKind.Unspecified).AddTicks(535), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = 0L
                        });
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserPetEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdditionalPhotosURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Allergies")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("ApproximateAge")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNeutered")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPets");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.VeterinaryAppointmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppointmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PetId")
                        .HasColumnType("bigint");

                    b.Property<string>("Prescriptions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Treatment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("VeterinaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("VeterinaryAppointments");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.UserPetEntity", b =>
                {
                    b.HasOne("PetRadar.Core.Data.Entities.UserEntity", "ParentUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("PetRadar.Core.Data.Entities.VeterinaryAppointmentEntity", b =>
                {
                    b.HasOne("PetRadar.Core.Data.Entities.UserPetEntity", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
